- name: Restart server
  listen: "Restart server & wait for it to restart"
  command: /sbin/shutdown -r +1
  async: 1
  poll: 0
  become: yes
- name: Wait for server to restart
  listen: "Restart server & wait for it to restart"
  wait_for_connection:
    delay: 60
    timeout: 300
  

