---

galaxy_info:
  role_name: docker
  author: arillso
  description: Installed and Configuriet then docker deamon on different Linux systems.
  license: MIT
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions:
        - 5
        - 6
    - name: Fedora
      versions:
        - 16
        - 17
        - 18
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
    - name: Debian
      versions:
        - wheezy

  galaxy_tags:
    - containers
    - compose
    - docker
    - packaging
    - system

dependencies: []
